[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "STRICT"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy-Report-Only = '''
    default-src 'self';

    font-src 'self' fonts.gstatic.com;
    frame-src 'self';
    img-src 'self' data:;
    media-src 'self';
    script-src 'self' 'unsafe-inline';
    style-src 'self' 'unsafe-inline' fonts.googleapis.com;

    base-uri 'none';
    connect-src 'none';
    form-action 'none';
    object-src 'none';'''

[build]
  command = "npm run generate"
  publish = "dist"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "development"

